# Generated by Django 5.2.3 on 2025-06-19 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RidePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="タイトル")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "departure_location",
                    models.CharField(max_length=100, verbose_name="出発地"),
                ),
                ("destination", models.CharField(max_length=100, verbose_name="目的地")),
                ("departure_time", models.DateTimeField(verbose_name="出発日時")),
                ("max_participants", models.IntegerField(verbose_name="最大参加者数")),
                (
                    "price_per_person",
                    models.IntegerField(blank=True, null=True, verbose_name="一人あたりの料金"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "募集中"),
                            ("cancelled", "キャンセル"),
                            ("completed", "完了"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "配車計画",
                "verbose_name_plural": "配車計画",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_location_name",
                    models.CharField(max_length=100, verbose_name="乗車場所名"),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="乗車場所緯度"
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="乗車場所経度"
                    ),
                ),
                (
                    "dropoff_location_name",
                    models.CharField(max_length=100, verbose_name="降車場所名"),
                ),
                (
                    "dropoff_latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="降車場所緯度"
                    ),
                ),
                (
                    "dropoff_longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="降車場所経度"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "ride_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rides.rideplan",
                        verbose_name="配車計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "参加情報",
                "verbose_name_plural": "参加情報",
                "unique_together": {("user", "ride_plan")},
            },
        ),
    ]
