# Generated by Django 5.2.3 on 2025-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rideplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "配車計画",
                "verbose_name_plural": "配車計画",
            },
        ),
        migrations.AddField(
            model_name="participation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AddField(
            model_name="rideplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "保留中"),
                    ("confirmed", "確定"),
                    ("cancelled", "キャンセル"),
                ],
                default="pending",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="rideplan",
            name="max_participants",
            field=models.PositiveIntegerField(default=4, verbose_name="最大参加者数"),
        ),
        migrations.AlterField(
            model_name="rideplan",
            name="price_per_person",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="一人あたりの料金"
            ),
        ),
        migrations.AlterField(
            model_name="rideplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "募集中"),
                    ("full", "定員満員"),
                    ("cancelled", "キャンセル"),
                    ("completed", "完了"),
                ],
                default="active",
                max_length=20,
                verbose_name="ステータス",
            ),
        ),
    ]
