# Generated by Django 5.2.3 on 2025-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_rideplan_options_participation_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="dropoff_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="降車場所緯度",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="dropoff_location_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="降車場所名"
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="dropoff_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="降車場所経度",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="pickup_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="乗車場所緯度",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="pickup_location_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="乗車場所名"
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="pickup_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="乗車場所経度",
            ),
        ),
    ]
