# Generated by Django 5.2.3 on 2025-06-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_alter_participation_dropoff_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rideplan",
            name="deadline_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="締切日時"),
        ),
    ]
