# Generated by Django 5.2.3 on 2025-07-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_rideplan_deadline_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="rideplan",
            name="delay_minutes",
            field=models.PositiveIntegerField(default=0, verbose_name="遅延時間（分）"),
        ),
        migrations.AddField(
            model_name="rideplan",
            name="delay_updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="遅延情報更新日時"),
        ),
        migrations.AddField(
            model_name="rideplan",
            name="is_delayed",
            field=models.BooleanField(default=False, verbose_name="遅延中"),
        ),
    ]
