# Generated by Django 5.2.3 on 2025-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_group_rideplan_group_groupmembership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rideplan",
            name="group",
        ),
        migrations.AddField(
            model_name="rideplan",
            name="groups",
            field=models.ManyToManyField(
                blank=True, to="rides.group", verbose_name="表示グループ"
            ),
        ),
    ]
