# Generated by Django 5.2.3 on 2025-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0007_remove_rideplan_group_rideplan_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="rideplan",
            name="delay_possibility",
            field=models.BooleanField(default=False, verbose_name="遅延の可能性あり"),
        ),
        migrations.AddField(
            model_name="rideplan",
            name="delay_possibility_updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="遅延可能性更新日時"),
        ),
    ]
